import re
from pathlib import Path

from docutils import nodes as docutils_nodes
from sphinx.application import Sphinx
from sphinx_design.icons import fontawesome
from sphinx_design.shared import PassthroughTextElement
from sphinx_markdown_builder.translator import MarkdownTranslator

_MARKDOWN_IMAGE_RE = re.compile(r"(!\[[^\]]*\]\()([^)\s]+)(\))")


def _rewrite_file(path: Path, images: dict, imagedir: str) -> None:
    text = path.read_text(encoding="utf-8")

    def replace(match: "re.Match[str]") -> str:
        prefix, uri, suffix = match.groups()
        entry = images.get(uri)
        if entry is None:
            # Notebooks have the wrong prefix but are not in env.images. This is a hack
            # to point it to the right place.
            uri: str = uri.replace("_build/_markdown_build/", "/")
            return f"{prefix}{uri}{suffix}"

        _docnames, unique_name = entry
        new_uri = f"{imagedir}/{unique_name}"
        return f"{prefix}{new_uri}{suffix}"

    new_text = _MARKDOWN_IMAGE_RE.sub(replace, text)
    if new_text != text:
        path.write_text(new_text, encoding="utf-8")


def _fix_markdown_image_links(app: Sphinx, exception: Exception | None) -> None:
    """Fix up image links in the Markdown files generated by sphinx-llm.

    ``sphinx_markdown_builder`` (used by ``sphinx-llm`` to produce the per-page
    ``.html.md`` copies) writes image URIs verbatim from the doctree: a path relative to
    ``srcdir`` (e.g. ``images/profiles/image.jpg``).

    ``env.images`` contains the correct mappings.
    """
    if exception is not None:
        return
    if not app.builder or app.builder.name not in ("html", "dirhtml"):
        return

    images = app.env.images
    imagedir = app.builder.imagedir
    outdir = Path(app.builder.outdir)

    md_files = [p for p in outdir.rglob("*.md") if p.is_file()]
    llms_full_txt = outdir / "llms-full.txt"
    if llms_full_txt.is_file():
        md_files.append(llms_full_txt)

    for md_file in md_files:
        _rewrite_file(md_file, images, imagedir)


def fix_markdown_image(app: Sphinx) -> None:
    """Fix up image links in the Markdown files generated by sphinx-llm."""
    app.connect("build-finished", _fix_markdown_image_links)


def fix_notebook_output_markdown(app: Sphinx) -> None:
    """Fix sphinx_llm to render notebook cell outputs as markdown.

    myst-nb emits separate `.. raw:: html`, `.. raw:: latex`, and `.. raw:: text`
    blocks for each cell output, one per builder. Every other translator only renders
    the block matching its own format, but sphinx_markdown_builder renders raw nodes
    unconditionally, so all three duplicates end up concatenated in the markdown
    output. Patch it to skip the html/latex ones, keeping the plain-text one.
    """

    def visit_raw(self, node):
        if node.get("format") in ("html", "latex"):
            raise docutils_nodes.SkipNode

    def _passthrough(self, node):
        pass

    MarkdownTranslator.visit_raw = visit_raw
    MarkdownTranslator.depart_raw = _passthrough


def fix_unsupported_markdown_nodes(app: Sphinx) -> None:
    """Teach sphinx-llm's Markdown builder about nodes it doesn't recognise.

    ``sphinx_design`` only registers visitors for the html/latex/text/man/texinfo
    builders (see ``sphinx_design.extension.setup_extension``), and
    ``sphinx_markdown_builder`` has no support for docutils' citation or figure
    caption nodes. Without visitors, sphinx_markdown_builder's ``unknown_visit``
    logs a warning and drops the whole subtree, silently losing card titles,
    icons, citation text (and its anchor, breaking the citation reference link),
    and figure captions.
    """

    def _noop(self, node):
        pass

    # Card/link titles and `:fas:`/`:fab:` icons: nothing sensible to render as
    # Markdown, so just skip over them like the text/man/texinfo builders do.
    app.add_node(
        PassthroughTextElement,
        markdown=(_noop, _noop),
        override=True,
    )
    app.add_node(fontawesome, markdown=(_noop, _noop), override=True)

    # Citations (`.. [key] ...`) are structurally the same as footnotes, which
    # MarkdownTranslator already supports.
    def visit_citation(self, node):
        self.visit_footnote(node)

    def depart_citation(self, node):
        self.depart_footnote(node)

    MarkdownTranslator.visit_citation = visit_citation
    MarkdownTranslator.depart_citation = depart_citation

    # Figure captions have no dedicated visitor; render them like a paragraph.
    def visit_caption(self, node):
        self.visit_paragraph(node)

    def depart_caption(self, node):
        self.depart_paragraph(node)

    MarkdownTranslator.visit_caption = visit_caption
    MarkdownTranslator.depart_caption = depart_caption

    # Generic `{admonition}` directives (e.g. the "See also" boxes in the
    # notebook index pages) produce a plain docutils `admonition` node with an
    # explicit `title` child, unlike `note`/`warning`/etc., which
    # sphinx_markdown_builder already renders as "#### NOTE" boxes and have no
    # title child of their own. There's no visitor for the generic node at
    # all, so descend into it like a plain container: the title child renders
    # as a heading and the body renders as normal Markdown.
    def visit_admonition(self, node):
        pass

    def depart_admonition(self, node):
        pass

    MarkdownTranslator.visit_admonition = visit_admonition
    MarkdownTranslator.depart_admonition = depart_admonition
