import re
from pathlib import Path
from typing import Optional

from nbsphinx import CodeAreaNode, FancyOutputNode
from docutils import nodes as docutils_nodes
from sphinx_markdown_builder.translator import MarkdownTranslator
from sphinx.application import Sphinx

_MARKDOWN_IMAGE_RE = re.compile(r"(!\[[^\]]*\]\()([^)\s]+)(\))")


def _rewrite_file(path: Path, images: dict, imagedir: str) -> None:
    text = path.read_text(encoding="utf-8")

    def replace(match: "re.Match[str]") -> str:
        prefix, uri, suffix = match.groups()
        entry = images.get(uri)
        if entry is None:
            # Notebooks have the wrong prefix but are not in env.images. This is a hack
            # to point it to the right place.
            uri: str = uri.replace("_build/_markdown_build/", "/")
            return f"{prefix}{uri}{suffix}"

        _docnames, unique_name = entry
        new_uri = f"{imagedir}/{unique_name}"
        return f"{prefix}{new_uri}{suffix}"

    new_text = _MARKDOWN_IMAGE_RE.sub(replace, text)
    if new_text != text:
        path.write_text(new_text, encoding="utf-8")


def _fix_markdown_image_links(app: Sphinx, exception: Optional[Exception]) -> None:
    """Fix up image links in the Markdown files generated by sphinx-llm.

    ``sphinx_markdown_builder`` (used by ``sphinx-llm`` to produce the per-page
    ``.html.md`` copies) writes image URIs verbatim from the doctree: a path relative to
    ``srcdir`` (e.g. ``images/profiles/image.jpg``).

    ``env.images`` contains the correct mappings.
    """
    if exception is not None:
        return
    if not app.builder or app.builder.name not in ("html", "dirhtml"):
        return

    images = app.env.images
    imagedir = app.builder.imagedir
    outdir = Path(app.builder.outdir)

    md_files = [p for p in outdir.rglob("*.md") if p.is_file()]
    llms_full_txt = outdir / "llms-full.txt"
    if llms_full_txt.is_file():
        md_files.append(llms_full_txt)

    for md_file in md_files:
        _rewrite_file(md_file, images, imagedir)


def fix_markdown_image(app: Sphinx) -> None:
    """Fix up image links in the Markdown files generated by sphinx-llm."""
    app.connect("build-finished", _fix_markdown_image_links)


def fix_nbsphinx(app: Sphinx) -> None:
    """Fix sphinx_llm to render nbsphinx notebooks as markdown."""

    def _passthrough(self, node):
        pass

    app.add_node(CodeAreaNode, markdown=(_passthrough, _passthrough), override=True)
    app.add_node(FancyOutputNode, markdown=(_passthrough, _passthrough), override=True)

    # nbsphinx emits separate `.. raw:: html`, `.. raw:: latex`, and `.. raw:: text`
    # blocks for each cell output, one per builder. Every other translator only renders
    # the block matching its own format, but sphinx_markdown_builder renders raw nodes
    # unconditionally, so all three duplicates ended up concatenated in the markdown
    # output once the CodeAreaNode/FancyOutputNode wrappers above stopped hiding them.
    # Patch it to skip the html/latex ones, keeping the plain-text one.
    def visit_raw(self, node):
        if node.get("format") in ("html", "latex"):
            raise docutils_nodes.SkipNode

    MarkdownTranslator.visit_raw = visit_raw
    MarkdownTranslator.depart_raw = _passthrough
